spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/peini?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: password
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      max-idle: 20
      min-idle: 5
      max-wait-millis: 20000
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy


server:
  port: 10086

shiro:
  realm:
    jdbc:
      enabled: true

logging:
  level:
    org:
      apache:
        shiro: debug
      hibernate:
        SQL: debug

mybatis:
  mapper-locations:
