spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peini?useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: password
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      max-idle: 20
      min-idle: 5
      max-wait-millis: 20000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 10086
